/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.example.4-2.unsafeDefs'

export { $nsid }

type Def$0 = 9

export type { Def$0 as TypeOf9 }

const def$0 = /*#__PURE__*/ l.literal(9)

export { def$0 as '9' }

type ObJeCT = { $type?: 'com.example.4-2.unsafeDefs#ob-je-c$t' }

export type { ObJeCT }

const obJeCT = /*#__PURE__*/ l.typedObject<ObJeCT>(
  $nsid,
  'ob-je-c$t',
  /*#__PURE__*/ l.object({}),
)

export { obJeCT as 'ob-je-c$t' }

type FfRiNG = string

export type { FfRiNG }

const ffRiNG = /*#__PURE__*/ l.string()

export { ffRiNG as 'ff-ri-n.g' }
