/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.example.kitchenSink'

export { $nsid }

/** A record */
type Main = {
  $type: 'com.example.kitchenSink'
  object: Object$0
  array: string[]
  boolean: boolean
  integer: number
  string: string
  bytes: Uint8Array
  cidLink: l.Cid
}

export type { Main }

/** A record */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    object: /*#__PURE__*/ l.ref<Object$0>((() => object$0) as any),
    array: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string()),
    boolean: /*#__PURE__*/ l.boolean(),
    integer: /*#__PURE__*/ l.integer(),
    string: /*#__PURE__*/ l.string(),
    bytes: /*#__PURE__*/ l.bytes(),
    cidLink: /*#__PURE__*/ l.cid(),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Object$0 = {
  $type?: 'com.example.kitchenSink#object'
  object: Subobject
  array: string[]
  boolean: boolean
  integer: number
  string: string
}

export type { Object$0 as Object }

const object$0 = /*#__PURE__*/ l.typedObject<Object$0>(
  $nsid,
  'object',
  /*#__PURE__*/ l.object({
    object: /*#__PURE__*/ l.ref<Subobject>((() => subobject) as any),
    array: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string()),
    boolean: /*#__PURE__*/ l.boolean(),
    integer: /*#__PURE__*/ l.integer(),
    string: /*#__PURE__*/ l.string(),
  }),
)

export { object$0 as object }

type Subobject = {
  $type?: 'com.example.kitchenSink#subobject'
  boolean: boolean
}

export type { Subobject }

const subobject = /*#__PURE__*/ l.typedObject<Subobject>(
  $nsid,
  'subobject',
  /*#__PURE__*/ l.object({ boolean: /*#__PURE__*/ l.boolean() }),
)

export { subobject }
