/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'com.example.parametersEnum'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  booleanCst: /*#__PURE__*/ l.literal(true),
  integerCst: /*#__PURE__*/ l.literal(42),
  integerEnum: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.enum([1, 2, 3])),
  stringCst: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.literal('foo')),
  stringEnum: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.enum(['foo', 'bar', 'baz']),
  ),
  arrayFalse: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.literal(false)),
  ),
  arrayIntCst: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.literal(42)),
  ),
  arrayIntEnum: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.enum([4, 5, 6])),
  ),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.payload()

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
