/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as ExampleKitchenSink from './kitchenSink.defs.js'

const $nsid = 'com.example.union'

export { $nsid }

/** A record */
type Main = {
  $type: 'com.example.union'
  unionOpen:
    | l.$Typed<ExampleKitchenSink.Object>
    | l.$Typed<ExampleKitchenSink.Subobject>
    | l.Unknown$TypedObject
  unionClosed:
    | l.$Typed<ExampleKitchenSink.Object>
    | l.$Typed<ExampleKitchenSink.Subobject>
}

export type { Main }

/** A record */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    unionOpen: /*#__PURE__*/ l.typedUnion(
      [
        /*#__PURE__*/ l.typedRef<ExampleKitchenSink.Object>(
          (() => ExampleKitchenSink.object) as any,
        ),
        /*#__PURE__*/ l.typedRef<ExampleKitchenSink.Subobject>(
          (() => ExampleKitchenSink.subobject) as any,
        ),
      ],
      false,
    ),
    unionClosed: /*#__PURE__*/ l.typedUnion(
      [
        /*#__PURE__*/ l.typedRef<ExampleKitchenSink.Object>(
          (() => ExampleKitchenSink.object) as any,
        ),
        /*#__PURE__*/ l.typedRef<ExampleKitchenSink.Subobject>(
          (() => ExampleKitchenSink.subobject) as any,
        ),
      ],
      true,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
